version: "3" 
services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - data_db:/var/lib/mysql
    networks: 
     -  inception_network
    restart: on-failure
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - data_wordpress:/www/wordpress
    depends_on:
      - wordpress
    networks: 
     -  inception_network
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - data_wordpress:/www/wordpress
    networks: 
     -  inception_network
    restart: on-failure
  adminer:
    build: requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8000:8000"
    networks: 
     -  inception_network
    restart: on-failure
  ftp:
    build: requirements/bonus/ftp
    image: ftp
    container_name: ftp
    volumes:
       - data_wordpress:/www/wordpress
    env_file:
      - .env
    ports:
      - "21:21"
      - "40000:40000"
    networks: 
     -  inception_network
    restart: on-failure
  redis:
    build: requirements/bonus/redis
    image: redis
    container_name: redis
    volumes:
      - data_wordpress:/www/wordpress
    ports:
      - "6379"
    networks: 
     -  inception_network
    depends_on:
      - wordpress
    restart: on-failure
  site_web:
    build: requirements/bonus/site_web
    image: site_web
    container_name: site_web
    ports:
      - "5000:5000"
    networks: 
     -  inception_network
    restart: on-failure
  portainer:
    build: requirements/bonus/portainer
    image: portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_portainer:/var/run/docker.sock
    ports:
      - "9443:9443"
networks:
  inception_network:
    driver: bridge

volumes:
  data_wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/zel-hach/data/wordpress
  data_db:
    driver_opts:
      o: bind
      type: none
      device: /home/zel-hach/data/mysql
  data_portainer:
    driver_opts:
      o: bind
      type: none
      device: /home/zel-hach/data/portainer