FROM alpine:3.11
RUN apk add wget
RUN wget https://github.com/portainer/portainer/releases/download/2.17.1/portainer-2.17.1-linux-amd64.tar.gz \
        && tar -xzvf portainer-2.17.1-linux-amd64.tar.gz\
        &&  rm portainer-2.17.1-linux-amd64.tar.gz \
        && chmod +x ./portainer/portainer
EXPOSE 9443
CMD ["./portainer/portainer"]